added styles gulp-less dz-05
SutorminAnton/dz-gulp-1 pull request #1
Opened 2018-02-02 20:28 UTC by SutorminAnton

2018-02-02 20:32 UTC, nobleworkshop requested changes
Надо поменять строчку с gulp.watch, в ней неверное название таска.

2018-02-02 20:32 UTC, nobleworkshop commented on gulpfile.js
> +    gulp.watch('./app/less/**/*.less', ['less']);
Здесь вызывается таск less которого уже нет. Надо поменять на styles.

2018-02-02 20:32 UTC, nobleworkshop commented
@SutorminAnton Сделал ревью, нужны правки

2018-02-02 20:45 UTC, SutorminAnton commented
@nobleworkshop. Правки сделал.

2018-02-03 11:24 UTC, nobleworkshop approved these changes
Looks good! Все верно!) Можно мержить!

2018-02-03 11:24 UTC, nobleworkshop commented
@SutorminAnton  Все верно!) Можно мержить!

2018-02-03 15:59 UTC, merged